import Head from 'next/head'
import { useEffect } from 'react';
import { main } from '@/scripts';
import { X, PaperPlaneRight } from '@phosphor-icons/react'
import { UserInfo } from '@/components/UserInfo';
import { Message } from '@/components/Message';


export default function Home() {
  useEffect(() => {
    main()
  }, []);

  return (
    <>
      <Head>
        <title>Message Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="app">
        <header id="top">
          <UserInfo name='Cecilia Sassaki' status='Online' />
          <div id="close-chat">
            <i className="ph-x-fill" title='Close Button'>
              <X weight='bold'></X>
            </i>
          </div>
        </header>


        <main id="messages">
          <div id="last-seen">
            <span>
              Hoje 11:30
            </span>
          </div>

          <div className="messages">
            <Message
              message='Tive uma ideia incrível para um projeto! 😍'
              hour='11:30'
              name='Cecília'
              type='received'
            />

            <Message
              message='Sério? Me conta mais.'
              hour='11:30'
              name='Você'
              type='sent'
            />

            <Message
              message='E se a gente fizesse um chat moderno e responsivo em apenas uma
              semana?'
              hour='11:31'
              name='Cecília'
              type='received'
            />

            <Message
              message='#boraCodar! 🚀'
              hour='11:32'
              name='Você'
              type='sent'
            />
          </div>
        </main>

        <footer>
          <form id="bottom">
            <input type="text" placeholder="Digite sua mensagem" />
            <button>
              <i className="ph-paper-plane-right-fill">
                <PaperPlaneRight weight='fill' />
              </i>
            </button>
          </form>
        </footer>
      </div>
    </>
  )
}
