import Head from 'next/head'
import { X } from '@phosphor-icons/react'
import { UserInfo } from '@/components/UserInfo';
import { MessagesView } from '@/components/MessagesView';
import { InputChat } from '@/components/InputChat';
import { MessageError } from '@/components/MessageError';

export default function Home() {

  return (
    <>
      <Head>
        <title>Message Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="app">
        <header id="top">
          <UserInfo name='Cecilia Sassaki' status='Online' />
          <div id="close-chat">
            <i className="ph-x-fill" title='Close Button'>
              <X weight='bold'></X>
            </i>
          </div>
        </header>

        <MessagesView >
          <MessageError />
        </MessagesView>

        <footer>
          <InputChat />
        </footer>
      </div>
    </>
  )
}
